" Syntax highlighting
"""""""""""""""""""""""""""""""""""""""
syntax on
set background=dark
let g:gruvbox_contrast_dark = 'hard'
colorscheme gruvbox

au BufNewFile,BufRead *.txx set filetype=cpp

" VTK files are xml
autocmd BufRead,BufNewFile *.vt* set filetype=xml

" Paraview state files are xml
autocmd BufRead,BufNewFile *.pvsm set filetype=xml

" Key bindings
"""""""""""""""""""""""""""""""""""""""
let mapleader=" "

nmap U <C-r>
nmap ; :
" browse buffer
map <leader>j :bnext<CR>
map <leader>k :bprevious<CR>

" File browser
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
map <leader>o :Vexplore<CR>

" Go to next empty line with enter
nnoremap <expr> <CR> empty(&buftype) ? '}' : '<CR>'

" Display number of search occurence
map <leader>c :%s///gn<CR>

" Editor
"""""""""""""""""""""""""""""""""""""""
" Appearance
set ruler                  "Show the cursor position all the time
set cursorline             "Change the current line background
set scrolloff=8            "Keep 8 line above and under the current one
set number                 "Show line numbers
set relativenumber         "Show relative line numbers
let &colorcolumn=120       "Highlight column 120
"hi ColorColumn ctermbg=darkgrey guibg=darkgrey 

" Features
set ignorecase             "Ignore case when searching
set smartcase              "Case sensitive if uppercase is asked
set hlsearch               "Have vim highlight the target of a search
set incsearch              "Show search matches as you type
set wildignorecase				 "Ignore case in file name completion

" Indentation
"""""""""""""""""""""""""""""""""""""""
set tabstop=2              "Number of spaces a TAB in the text stands for
set shiftwidth=2           "Number of spaces used for each step of (auto)indent
set expandtab              "Tabs to spaces
set autoindent

" Misc
"""""""""""""""""""""""""""""""""""""""
set laststatus=2           "Always show status line
set showcmd

set autowrite              "Automatically write a file when leaving a modified buffer
set autoread               "Reload the file if changed from the outside
set confirm                "Start a dialog when a command fails (here when quit command fails)

set wildmenu
set wildmode=longest,full

set encoding=utf-8
set fileencoding=utf-8

set undofile

" Plugins
"""""""""""""""""""""""""""""""""""""""
" nice to have:
" - tpope commentary : toggle comments
" - tpope surround 
" - ctrlpvim : fuzzyfinder to open file
" Bonus:
" - ale : syntax checker
" - jedi : python completion 
" - nerdtree : file tree

